FROM opensearchproject/opensearch-dashboards:latest

#ENV OPENSEARCH_HOSTS=["http://opensearch-node1:9200"]
# disables security dashboards plugin in OpenSearch
#ENV DISABLE_SECURITY_DASHBOARDS_PLUGIN=true

RUN mkdir WORK_REPO
#WORKDIR /WORK_REPO
ADD res .
