query {
  mdhSearch(
    filterFunctions: []
  ) {
    totalFilesCount
    returnedFilesCount
    instanceName
    timeZone
    fixedReturnColumnSize
    limitedByLicensing
    queryStatusAsText
    dataTypes {
      name
      type
    }
    files {
      metadata {
        name
        value
      }
    }
  }
}
