query {
  mdhSearch(
    filterFunctions: []
    filterLogicOption: AND
    selectedTags: [
      "FileName"
      "FileSize"
      "MIMEType"
      "FileInodeChangeDate"
      "SourceFile"
    ]
    limit: 100
  ) {
    totalFilesCount
    returnedFilesCount
    instanceName
    timeZone
    fixedReturnColumnSize
    limitedByLicensing
    queryStatusAsText
    dataTypes {
      name
      type
    }
    files {
      metadata {
        name
        value
      }
    }
  }
}
