query {
    mdhSearch(
        filterFunctions: []
        limit: 200
    ) {
        totalFilesCount
        returnedFilesCount
        instanceName
        timeZone
        fixedReturnColumnSize
        limitedByLicensing
        queryStatusAsText
        dataTypes {
            name
            type
        }
        files {
            metadata {
                name
                value
            }
        }
    }
}
