#
#        query {
#            mdhSearch(
#                filterFunctions: [
#                    {
#                        tag: "MdHTimestamp",
#                        value: "2023-06-10 15:23:43",
#                        operation: EQUAL,
#                        dataType: TS
#                    }
#                ],
#                filterLogicOption: AND,
#                limit: 2
#            ) {
#                totalFilesCount
#                returnedFilesCount
#                instanceName
#                timeZone
#                fixedReturnColumnSize
#                limitedByLicensing
#                queryStatusAsText
#                dataTypes {
#                    name
#                    type
#                }
#                files {
#                    metadata {
#                        name
#                        value
#                    }
#                }
#            }
#        }
#
