on:
  push:
    branches: [feature/CI_CD_pipeline]
    paths:
      - 'test.py'
      - 'lint.py'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint pytest
      - name: Lint with pylint
        run: |
          pylint_result=$(pylint res/mdh_extraction.py --output-format=parseable)
          echo "$pylint_result"
          if [[ $pylint_result =~ "rated at 10.00/10" ]]; then
            echo "Linting passed!"
          else
            echo "Linting failed!"
            exit 1
          fi      # - name: Run pytest suite
      #   run: |
      #     pytest pytest_test.py

